export * from "./Heading";
export * from "./Title";
export * from "./Box";
export * from "./Grid";
export * from "./Flex";
export * from "./Card";
export * from "./Mainheading";
export * from "./Mainheading2";
export * from "./Mainheading3";